baseURL = 'https://docs.comfylang.org/'
languageCode = 'en-us'
title = 'Comfy Language Documentation'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false